### ISSUE TITLE
为什么我运行代码报错，ValueError: 150001 is not in list 

### ISSUE THREAD

**Issue by LCK-Lin** [thinksoso/ChatGLM-Instruct-Tuning#5]
Traceback (most recent call last):
  File "run_clm.py", line 564, in <module>
    main()
  File "run_clm.py", line 512, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/conda/envs/GLM_instruct/lib/python3.8/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/opt/conda/envs/GLM_instruct/lib/python3.8/site-packages/transformers/trainer.py", line 1902, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/envs/GLM_instruct/lib/python3.8/site-packages/transformers/trainer.py", line 2645, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/envs/GLM_instruct/lib/python3.8/site-packages/transformers/trainer.py", line 2677, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/envs/GLM_instruct/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/liangcy1@xiaopeng.com/lck/ChatGLM-Instruct-Tuning/modeling_chatglm.py", line 1033, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/envs/GLM_instruct/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/liangcy1@xiaopeng.com/lck/ChatGLM-Instruct-Tuning/modeling_chatglm.py", line 836, in forward
    mask_position = seq.index(mask_token)
ValueError: 150001 is not in list
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /workspace/liangcy1@xiaopeng.com/lck/ChatGLM-Instruct-Tuning/wandb/offline-run-20230408_040222-i5caj5n7
wandb: Find logs at: ./wandb/offline-run-20230408_040222-i5caj5n7/logs

**Comment by changsha2999** [comment]
same

**Comment by LCK-Lin** [comment]
> same

这个是由于hugging Face的ChatGLM-6B代码有更新，把把最新的模型替换一下就可以了

**Comment by changsha2999** [comment]
modify：ChatGLM-Instruct-Tuning/modeling_chatglm.py", line 836 to MASK, gMASK = 130000, 130001

**Comment by LCK-Lin** [comment]
> modify：ChatGLM-Instruct-Tuning/modeling_chatglm.py", line 836 to MASK, gMASK = 130000, 130001
还有两个文件更新了，[tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenization_chatglm.py)和[tokenizer_config.json](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenizer_config.json)这两个替换了吗

**Comment by changsha2999** [comment]
> > modify：ChatGLM-Instruct-Tuning/modeling_chatglm.py", line 836 to MASK, gMASK = 130000, 130001
> > 还有两个文件更新了，[tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenization_chatglm.py)和[tokenizer_config.json](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenizer_config.json)这两个替换了吗

谢谢你的信息，这两个文件没有直接在tuning项目中引用，我估计已经直接使用了缓存中的最新的huggingface这两个文件。你那边运行成功了吗？我这边跑起来的时候一下就吃完了30G显存，把模型改成load_in_8bit则出各种问题，还未跑起来，请问有何建议，谢谢~

**Comment by Hasen-dc** [comment]
一样的问题

**Comment by YSLLYW** [comment]
> 130000, 130001

您这边成功运行了吗

**Comment by YSLLYW** [comment]
> > modify：ChatGLM-Instruct-Tuning/modeling_chatglm.py", line 836 to MASK, gMASK = 130000, 130001
> > 还有两个文件更新了，[tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenization_chatglm.py)和[tokenizer_config.json](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenizer_config.json)这两个替换了吗
替换成最新的，微调还是报错：ValueError: 130004 is not in list

**Comment by KyrieWang7** [comment]
ValueError: Unrecognized configuration class <class 'transformers_modules.model.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig,这个报错是因为什么了

**Comment by KyrieWang7** [comment]
> 

现在跑通了吗
